# Site settings
title: Yale Medical Centre
email: yalemed1280@yahoo.ca
description: The Yale Medical Centre is an addiction clinic providing Methadone and Suboxone maintenance treatment.
url: "yalemedicalcentre.com"

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
